### ISSUE TITLE
Could not resolve dependencies for project -starter-admin:jar:6.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by lesvere** [BroadleafCommerce/ReactStarter#13]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:44 min
[INFO] Finished at: 2019-07-21T01:30:50+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project boot-react-starter-admin: Could not resolve dependencies for project -starter-admin:jar:6.0.0-SNAPSHOT: Could not find artifact com.mycompany:boot-react-starter-core:jar:6.0.0-SNAP (http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by frostyandy2k** [comment]
You need to execute `mvn clean install` in the root folder, like the documentation says. However, that doesn't work for master and `develop-5.2.x` due to other errors. Only `develop-6.0.x` seems to work.

   > cd <path to ReactStarter>
   > mvn clean install
   > cd api
   > mvn spring-boot:run

**Comment by frostyandy2k** [comment]
Also, make sure you are running Java 8 for the dependency resolution and run.

**Comment by linuxidefix** [comment]
FTR, admin works properly in develop-6.0.x.
This issue can be closed.
