### ISSUE TITLE
Http vs Https in broadleaf admin for org.springframework.mobile:spring-mobile-device: dependency

### ISSUE THREAD

**Issue by conandc11** [BroadleafCommerce/ReactStarter#22]
adleaf-presentation-2.0.0-GA.pom
Downloading from public releases: http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-presentation/2.0.0-GA/broadleaf-presentation-2.0.0-GA.pom
Downloaded from public releases: http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-presentation/2.0.0-GA/broadleaf-presentation-2.0.0-GA.pom (5.6 kB at 3.9 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Broadleaf Spring Boot React Starter 6.0.0-SNAPSHOT:
[INFO]
[INFO] Broadleaf Spring Boot React Starter ................ SUCCESS [  0.988 s]
[INFO] React Core Starter ................................. SUCCESS [01:12 min]
[INFO] Admin Starter ...................................... FAILURE [ 12.084 s]
[INFO] React API Starter .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2020-02-11T16:13:51+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project boot-react-starter-admin: Could not resolve dependencies for project com.mycompany:boot-react-starter-admin:jar:6.0.0-SNAPSHOT: Failed to collect dependencies at org.broadleafcommerce:broadleaf-framework-web:jar:6.0.5-GA -> org.springframework.mobile:spring-mobile-device:jar:2.0.0.M3: Failed to read artifact descriptor for org.springframework.mobile:spring-mobile-device:jar:2.0.0.M3: Could not transfer artifact org.springframework.mobile:spring-mobile-device:pom:2.0.0.M3 from/to spring-milestones (http://repo.spring.io/milestone): Authorization failed for http://repo.spring.io/milestone/org/springframework/mobile/spring-mobile-device/2.0.0.M3/spring-mobile-device-2.0.0.M3.pom 403 Forbidden -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :boot-react-starter-admin

Just started with broadleaf but broadleaf is not able to hit the given  http://repo.spring.io/milestone/org/springframework/mobile/spring-mobile-device/2.0.0.M3/spring-mobile-device-2.0.0.M3.pom
because the repo is picking up only https. I Hope there is a quick fix for this. Help Pls.

**Comment by phillipuniverse** [comment]
This was resolved in core Broadleaf at https://github.com/BroadleafCommerce/BroadleafCommerce/commit/adcabd8da183fdca82e3a9141caa76a6740d7e62. To take advantage of it, update the root pom.xml to target `6.0.8-GA` of `broadleaf-boot-starter-parent` which is the latest release.

@danielcolgrove

**Comment by danielcolgrove** [comment]
Update merged.  Thanks @phillipuniverse.
