### ISSUE TITLE
failed in execute `mvn spring-boot:run`

### ISSUE THREAD

**Issue by miaopeng** [BroadleafCommerce/ReactStarter#8]
Error Logs: 
[ERROR] Failed to execute goal on project boot-react-starter-api: Could not resolve dependencies for project com.mycompany:boot-react-starter-api:jar:1.0.0-SNAPSHOT: Failure to find com.mycompany:boot-react-starter-core:jar:1.0.0-SNAPSHOT in http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of public snapshots has elapsed or updates are forced -> [Help 1]

Can not find com.mycompany:boot-react-starter-api:jar:1.0.0-SNAPSHOT in http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/

**Comment by ncrum** [comment]
@miaopeng just checking, but did you build the maven project first using `mvn clean install` in the root directory?

**Comment by miaopeng** [comment]
@ncrum yes, I did.

**Comment by ncrum** [comment]
@miaopeng The error you posted indicates it's not finding the `com.mycompany:boot-react-starter-core:jar:1.0.0-SNAPSHOT` jar. This jar is built by this maven build process, unless that build failed. Did you have any errors when you ran `mvn clean install` in the `ReactStarter/` directory?

**Comment by miaopeng** [comment]
Try rerun `mvn clean install` and error are gone, @ncrum thx, this issue is closed.
