### ISSUE TITLE
Not able to start API with mvn

### ISSUE THREAD

**Issue by sosproduction** [BroadleafCommerce/ReactStarter#9]
Have gotten demo site working great with just Java/Spring/Hibernate.  But it seems the /api implementation differs in some way in the React branch.  Tried to use mvn spring-boot:run and it fails to start the api.  Any ideas?  

Failed to execute goal on project boot-react-starter-api: Could not resolve dependencies for project com.mycompany:boot-react-starter-api:jar:1.0.0-SNAPSHOT: Failure to find com.mycompany:boot-react-starter-core:jar:1.0.0-SNAPSHOT in http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of public snapshots has elapsed or updates are forced

**Comment by cja769** [comment]
It looks like you didn't build the core maven project first therefore it couldn't be found when building and starting the api project.
```
cd <path to repo>/ReactStarter;
mvn clean install;
cd api;
mvn spring-boot:run
```
I'll update the README.md to indicate that the core project needs to be built first either by building from the root pom or building from the core pom.

**Comment by sosproduction** [comment]
Doh.  Sorry Jay.  Leave it to the newbs. :) . Thanks for the explanation.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cja769** [comment]
Haha no problem. It's a very common mistake.
